name: 'The Cool GH Releases Assets action'
description: 'Download/Uploads Releases Assets - A more complete action for Github releases Assets'
inputs:
  github_token:
    description: 'Github secret used for operations'
    required: true
  mode:
    description: 'Indicates if you want to download or upload Assets.'
    required: true
    default: 'download'
  assets:
    description: 'Absolute path to file. Multiple files can be specified using a semicolon as separator.'
    required: true
  tag:
    description: 'Tag used for download/upload assets'
    required: false
  body_mrkdwn:
    description: 'Description markdown used for new releases'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  icon: 'box'  
  color: 'blue'
