name: 'Check suite'
on:
  check_suite:
    types: [completed]

env:
  THE_GITHUB_CONTEXT: ${{ toJson(github) }}

jobs:
  something:
    name: 'some job'
    runs-on: ubuntu-latest

    steps:
      - name: Print context
        run: echo ${{ env.THE_GITHUB_CONTEXT }}