name: 'Fake status'
on:
  push

jobs:
  something:
    name: 'some job'
    runs-on: ubuntu-latest
    env:
      AUTH_HEADER: "Authorization: token ${{ secrets.GITHUB_OAUTH_TOKEN }}"
      ASSET_URL: "https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }}"
      DATA: >- 
        {
          "state": "success",
          "target_url": "https://example.com/build/status",
          "description": "The build succeeded!",
          "context": "continuous-integration/jenkins"
        }
    steps:
      - name: Post status
        run: >-
          echo "curl -L -X POST
          -H \"Content-Type: application/json\"
          -H \"${{ env.AUTH_HEADER }}\"
          -d '${{ env.DATA }}'
          \"${{ env.ASSET_URL }}\""
      - name: Post status
        run: >-
          curl -L -X POST
          -H "Content-Type: application/json"
          -H "${{ env.AUTH_HEADER }}"
          -d '${{ env.DATA }}'
          "${{ env.ASSET_URL }}"