name: 'Test before build'
on:
  push: 
    branches: 
      - master
    paths-ignore:
      - 'README.md'
      - '.github/**'
      - '.vscode/**'
  pull_request:
    branches: 
      - master

env:
  tag_for_tests: Test-${{ github.head_ref || github.ref || github.sha }}

jobs:
  build:
    name: 'Build dist for testing'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker build --target builder -t gh-action-builder .
          
      - name: Generate new dist folder & files
        run: |
          mkdir new-dist
          docker run --rm -v ${PWD}/new-dist:/usr/src/app/dist gh-action-builder

      - name: Save dist folder
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: ./new-dist/
  tests:
    runs-on: ubuntu-latest
    name: Test action modes
    needs: build
    env:
      TEST_TEXT: "Asset replaced correctly"

    steps:
      - name: Checkout # To use this repository's private action, you must check out the repository
        uses: actions/checkout@v2

      - name: Delete old dist
        run: rm -rf dist

      - name: Download dist from build job
        uses: actions/download-artifact@v1
        with:
          name: dist

      - name: Prepare files for tests
        run: |
          echo "${{env.TEST_TEXT}}" > "./src/README.md"

      - name: It should create a release with assets README.md and LICENCE
        id: test_create
        uses: ./ # Uses the action in the root directory
        with:
          mode: update
          isPrerelease: true
          tag_name: ${{ env.tag_for_tests }}
          release_name: Testing release action
          body_mrkdwn: "### It works!\n Wow, it worked like a charm 🎉"
          assets: README.md;LICENSE|text/plain;
          github_token: ${{ github.token }}

      - name: It should edit release name, add asset build.yml & replace README.md with a new one 
        uses: ./ # Uses the action in the root directory
        with:
          mode: update
          isPrerelease: true
          replace_assets: true
          releaseId: ${{ steps.test_create.outputs.releaseId }}
          release_name: Testing edit of a release
          assets: .github/workflows/build.yml;src/README.md
          github_token: ${{ github.token }}

      - name: It should download assets README.md, LICENCE, build.yml from Test release 
        uses: ./ # Uses the action in the root directory
        with:
          tag_name: ${{ env.tag_for_tests }}
          assets: README.md|dowloaded_README.md;LICENSE|dowloaded_LICENSE;build.yml|build.yml
          github_token: ${{ github.token }}
      - name: Confirm that files are correct
        run: |
          if [ "$(cat dowloaded_README.md)" != "${{env.TEST_TEXT}}" ]; then exit 1; fi
          if [ "$(cat dowloaded_LICENSE)" != "$(cat LICENSE)" ]; then exit 1; fi
          if [ "$(cat build.yml)" != "$(cat .github/workflows/build.yml)" ]; then exit 1; fi

      - name: It should download assets from another repo cards.json from Test release
        uses: ./ # Uses the action in the root directory
        with:
          assets: cards.json|dowloaded_cards.json
          github_token: ${{ secrets.DBS_SCRAPER_TOKEN }}
          repository: hay-espacio-en-el-taco/dbs-scraper
      - name: Confirm that downloaded files are correct
        run: |
          if [ ! -f dowloaded_cards.json ] || [ ! $(wc -c < dowloaded_cards.json) -ge 50000 ]; then exit 1; fi

      - name: It should delete release with tag Test 
        uses: ./ # Uses the action in the root directory
        with:
          mode: delete
          tag_name: ${{ env.tag_for_tests }}
          github_token: ${{ github.token }}

      - name: Trigger status event if master branch
        if: github.ref == 'refs/heads/master'
        run: >-
          curl -L -X POST 
          -H "Content-Type: application/json"
          -H "Authorization: token ${{ secrets.GITHUB_OAUTH_TOKEN }}"
          -d '{
            "state": "success",
            "target_url": "https://github.com/${GITHUB_REPOSITORY}/actions?query=workflow%3A\"Test+action+modes\"",
            "description": "All tests passed", "context": "test-suite/pass"
          }'
          "https://api.github.com/repos/${GITHUB_REPOSITORY}/statuses/${GITHUB_SHA}"
